import './globals.css';
import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import Navbar from '@/app/components/navbar/Navbar';
import ClientOnly from '@/app/components/ClientOnly';
import Modal from '@/app/components/modals/modal';
import RegisterModal from '@/app/components/modals/RegisterModel';
import LoginModal from '@/app/components/modals/LoginModel';
import ToasterProvider from './Providers/ToastProvider';
import getCurrentUser from './actions/getCurrentUser';

export const metadata: Metadata = {
  title: 'EasyStay',
  description: 'Generated by create next app',
};

const font = Nunito({
  subsets: ['latin'],
});


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser()
  return (
    <html lang='en'>
      <body className={font.className}>
        <ClientOnly>
          <ToasterProvider />
          <LoginModal />
          <RegisterModal />
          <Navbar currentUser={currentUser} />
        </ClientOnly>
        {children}
      </body>
    </html>
  );
}
