import './globals.css';
import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import Navbar from '@/components/navbar/Navbar';
import ClientOnly from '@/components/ClientOnly';
export const metadata: Metadata = {
  title: 'EasyStay',
  description: 'Generated by create next app',
};

const font = Nunito({
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={font.className}>
        <ClientOnly>  
          <Navbar />
        </ClientOnly>
        {children}
      </body>
    </html>
  );
}
