import './globals.css';
import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import Navbar from '@/components/navbar/Navbar';
import ClientOnly from '@/components/ClientOnly';
import Modal from '@/components/modals/modal';
import RegisterModal from '@/components/modals/RegisterModel';
import ToasterProvider from './Providers/ToastProvider';

export const metadata: Metadata = {
  title: 'EasyStay',
  description: 'Generated by create next app',
};

const font = Nunito({
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={font.className}>
        <ClientOnly>
          <ToasterProvider />
          <RegisterModal />
          <Navbar />
        </ClientOnly>
        {children}
      </body>
    </html>
  );
}
